config/routes.rb
Eris::Application.routes.draw do


  resources :feeds

  resources :tagged_urls

  resources :services do
    post "sort_feeds", :on => :member
    get "preview", :on => :member
  end

  match "fetch/tagged_urls" => "tagged_urls#index", :format => :rss, :as => :tagged_urls_fetch
  match "fetch/:slug" => "services#fetch", :as => :fetch

  root :to => 'services#index'

  get "tags" => "tagged_urls#tags", :as => "tags"

  get "r" => "redirector#index", :as => "redirect"  
end

app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible :name, :service_slug, :html, :css_style, :feed_ids, :live, :transform_course_code, :show_max_entries

  validates_presence_of :name, :service_slug
  validates_length_of :service_slug, :maximum => 30
  validates_format_of :service_slug, :with => /^[a-z\d_]+$/, :message => "can only be lowercase and alphanumeric with no spaces"
  validates_uniqueness_of :service_slug, :message => "the name must be unique"

  has_many :service_feed_bridges
  has_many :feeds, :through => :service_feed_bridges, :order => "position"

  def fetch_feeds(query_string)
    feeds_list = []
    self.feeds.each do |feed|
      f = feed.fetch(query_string, feed.name)

      feeds_list << f unless f.blank?
    end

    feeds_list
  end

  def destroy
    if live
      return
    else
      super
    end
  end

  def self.parse_course_codes(course_list)

    return Array.new if course_list == nil || !course_list.kind_of?(Array)

    courses = Array.new

    course_list.each do |course_code|
      course_parts = course_code.split("_")

      if course_parts.count > 5
        # 2011_GS_PPAL_Y_6100__3_A  - take the 3rd and 5th parts -> PPAL_6100  -- take 2nd and 3rd -> GS/PPAL and -- take 2nd, 3rd and 5th part GS/ppal6100
        courses.push (course_parts[2] + "_" + course_parts[4])
        courses.push (course_parts[1] + "/" + course_parts[2])
        courses.push (course_parts[1] + "/" + course_parts[2].downcase  + course_parts[4])
      end
    end

    return courses
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def sort_feeds
    service_id = params[:id]
    params[:feed].each_with_index do |id, index|
      ServiceFeedBridge.update_all({position: index+1}, {feed_id: id, service_id: service_id})
    end
    render nothing: true
  end

  def preview

    @service = Service.find(params[:id])
    render :layout => "simple"
  end

  def fetch

    @service = Service.find_by_service_slug(params[:slug])

    # make sure that non-nil services are ignored
    @service = Service.new unless @service


    @query_string = request.query_string

    if @service.transform_course_code

      if params[:courses].blank?
        request.parameters.merge!( { courses: "XXXX_XX_XXXX_X_XXXX__X_X_XX_X_XXXX_XX"})
        @query_string.sub!("courses=", "course=#{params[:courses]}")
      end

      if params[:courses]
        course_tags = Service.parse_course_codes(params[:courses].split(",")).join(",")
      else
        course_tags = ""
      end

      @query_string = @query_string + (@query_string.size > 1 ? "&" : "") + "tag=#{course_tags},#{params[:courses]}&program_codes=#{course_tags}"
    end


    @feeds = @service.fetch_feeds(@query_string)

    if @service.live?  || params[:preview]
      respond_to do |format|
          format.html { render :layout => "simple"}
          format.xml
          format.rss
          format.js
          format.json
      end
    else
      render :nothing => true
    end
  end

  def index
    @services = Service.all
  end

  def show
    @service = Service.find(params[:id])
  end

  def new
    @service = Service.new
  end

  def create
    feed_ids = params[:service][:feed_ids]
    params[:service].delete(:feed_ids)

    @service = Service.new(params[:service])
    if @service.save
      assign_feeds(feed_ids)
      redirect_to @service, :notice => "Successfully created service."
    else
      render :action => 'new'
    end
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])

    feed_ids = params[:service][:feed_ids]
    params[:service].delete(:feed_ids)

    if @service.update_attributes(params[:service])
      assign_feeds(feed_ids)
      redirect_to @service, :notice  => "Successfully updated service."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @service = Service.find(params[:id])
    if @service.live?
      redirect_to service_path(@service), :alert => "The service must be take off line, before you can delete it."
    else
      @service.destroy
      redirect_to services_url, :notice => "Successfully destroyed service."
    end
  end

  def assign_feeds(feed_ids)
    feed_ids.reject! { |e| e.nil? || e == "" || e.empty? }
    feed_ids = feed_ids.map { |e| e.to_i }
    @service.feeds.each do |f|
      if !feed_ids.include?(f.id)
        ServiceFeedBridge.where(service_id: @service.id, feed_id: f.id).each do |b|
          b.destroy
        end
      end
    end

    feed_ids.each do |i|
      if !@service.feed_ids.include?(i)
        if Feed.find(i)
          ServiceFeedBridge.create(service_id: @service.id, feed_id: i)
        end
      end
    end
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= simple_form_for @service, :html => { :class => 'form-vertical' } do |f| %>
  <fieldset>
	
	<div class="row">
		<div class="span6">
			<%= f.input :name, :input_html => {:class => "span4" } %>

			<%= f.input :service_slug, :input_html => {:class => "span3" } %>
			
			<%= f.input :show_max_entries, :collection => [1,2,3,4,5,6,7,8,9,10], :label => "Max Entries to Show", :hint => "On per feed basis" %>
			
			<hr/>
			<%= f.input :live, :wrapper => :checkbox %>
			
			<hr/>
			<h3>Transform Course Codes Into a Tag</h3>
			<br/>
			<%= f.input :transform_course_code, :wrapper => :checkbox  %>
			<p class="trivial">Eris will look for courses parameter with the list of comma separated courses ids and transform them into simplified version.</p>
			<p class="trivial">I.e. 2011_SC_NATS_Y_1670__6_A course id will be broken down to NATS_1670 and SC/NATS and passed on as a tag attribute to the feeds</p>
								
			
		</div>
		<div class="span6">
			<div class="control-group">
				<h3>Data Feeds</h3>
					<br/>
				<%= f.collection_check_boxes :feed_ids, Feed.all, :id, :name do |builder| 
					  builder.check_box + " " + builder.text + " <br/>".html_safe					
				 end %>
			</div>
			<hr/>
			<%= f.input :css_style, :as => :text, :input_html => {:class => "span5" }, :label => "Optional CSS"  %>
			
		</div>
	</div>
	
	
	
	
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', services_path, :class => 'btn' %>

	  <div class="float-right">
	  	<%= link_to 'Delete', service_path(@service), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger float-right' unless @service.new_record?%>
	  </div>
    </div>
  </fieldset>

	<% unless @service.new_record? %>
	<div class="float-right">
		<p><span class="label label-warning">Warning:</span> You can only delete a service that is not live. This action can be reversed.</p>
	</div>
	<% end %>

<% end %>

app/views/services/edit.html.erb
<% title "Edit Service" %>

<% title_html do %>
	<h1>Edit Service</h1>
<% end %>

<%= render :partial => 'form' %>

app/views/services/fetch.html.erb
<% title "#{@service.name} service" %>

<form action="<%= fetch_path(@service.service_slug) %>.html" method="get">
	<input name="courses" value=""/>
	<input type="submit" value="Go">
</form>

<% courses = params[:courses] ? params[:courses] : "2011_AP_SOSC_Y_4511_HJ" %>

<div class="push-down">
	<div id="eris_default_content">
		<div id="eris_loading_message">Loading...</div>
		<div id="eris_content_message" style="display: none;">
			<a href="https://www.library.yorku.ca">York University Libraries</a>
		</div>
	</div>
	<script type="text/javascript">
		setTimeout("document.getElementById('eris_loading_message').style.display='none'; document.getElementById('eris_content_message').style.display = 'block';",15000);
	</script>
	<script type="text/javascript" src="<%= fetch_path(@service.service_slug) %>.js?courses=<%= courses %>&preview=true"></script>
</div>

app/views/services/fetch.js.erb
// First Thing's First, CREATE THE CONTAINER FOR ERIS
document.write("<div id='eris-service-<%= @service.service_slug %>'></div>");


$(document).ready(function() {
	var service_slug = "<%= @service.service_slug %>";
	
	// hide default content
	$("#eris_default_content").hide();

	var json_content = <%= render template: "services/fetch", formats: :json %>;

				
	if (null != json_content.css) {	
		$("head").append("<style>" + json_content.css + "</style>");
	}
	
	$("#eris-service-" + service_slug).append(json_content.content);
			
});		

app/views/services/fetch.json.erb
<% @output = capture do %>
	<% @feeds.each do |feed| %>
		<% unless feed.entries.size == 0 && feed.description.blank? %>

			<% if feed.show_title? %>
				<h3 class="eris-feed-title-<%= feed.title.parameterize %>"><%= feed.title %></h3>
			<% end %>

			<% unless feed.description.blank? %>
				<div class="eris-feed-description-<%= feed.title.parameterize %>">
					<%= feed.description.gsub(/\r\n?/, "").html_safe  %>
				</div>
			<% end %>

			<% if feed.entries.size > 0 %>
				<ul class="eris-feed-entries-<%= feed.title.parameterize %>">
				<% feed.entries.each_with_index do |entry, index | %>
					<% if index < @service.show_max_entries %>
						<li><a href="<%= redirect_url(:protocol => 'https') %>/?<%= @query_string %>&url=<%=u entry.url %>" target="_blank"><%= entry.title %></a>
							<% unless entry.summary.blank? %><div class="summary"><%= entry.summary%></div><% end %>
						</li>
					<% end %>
				<% end %>
				</ul>
			<% end %>
		<% end %>
	<% end %>
<% end %>
{
	"valid": 1,
	"content": <%= raw @output.strip.to_json %>,
	<% unless @service.css_style.blank? %>
	"css" : <%= raw @service.css_style.to_json %>,
	<% end %>
	"link": "https://www.library.yorku.ca"
}

app/views/services/index.html.erb
<% title "Browse Services" %>
<% title_html do %>
	<h1>Services <%= link_to  new_service_path, :class => 'btn btn-success float-right' do%>
			<i class="icon-plus icon-white"></i>
			Create New Service
		<% end %>
	</h1>
<% end %>

<div class="row">
<% @services.each_with_index do |service, index| %>
	<div class="service standalone span5">
		<h2><%= service.name %> <small> <%= service.live? ? "Live" : "Disabled" %></small></h2>

		<table class="table table-condensed">
			<tr>
				<td class="trivial">Service Slug</td>
				<td><span class="badge badge-info"><%= service.service_slug %></span></td>
			</tr>
			<tr>
				<td class="trivial">Transform Course Code</td>
				<td><span class="badge badge-inverse"><%= service.transform_course_code? ? "Yes" : "No" %></span></td>
			</tr>
			<tr>
				<td class="trivial">Assigned Feeds</td>
				<td><span class="badge"><%= service.feeds.count%></span></td>
			</tr>
			<tr>
					<td class="trivial">Show Max Entries</td>
					<td><span class="badge badge-inverse"><%= service.show_max_entries%></span></td>
				</tr>
			<tr>
				<td></td>
				<td align="right">
				</td>
			</tr>
		</table>

		<%= link_to 'Service Details', service_path(service), :class => 'btn btn-xmini btn-primary' %>
		<%= link_to 'Update Service', edit_service_path(service), :class => 'btn btn-xmini' %>
		<%= link_to 'Preview', preview_service_path(service), :class => 'btn btn-info float-right'  %>
	</div>
<% end  %>
</div>

app/views/services/new.html.erb
<% title "New Service" %>
<% title_html do %>
	<h1>Add New Service</h1>
<% end %>

<%= render :partial => 'form' %>

app/views/services/preview.html.erb
<% title "#{@service.name} service" %>

<%= link_to "Back to details", @service %>

<hr/>
<h4>Preview</h4>
<hr/>
<div class="push-down">
	<div id="eris_default_content">
		<div id="eris_loading_message">Loading...</div>
		<div id="eris_content_message" style="display: none;">
			<a href="https://www.library.yorku.ca">York University Libraries</a>
		</div>
	</div>
	<script type="text/javascript">
		setTimeout("document.getElementById('eris_loading_message').style.display='none'; document.getElementById('eris_content_message').style.display = 'block';",15000);
	</script>
	<script type="text/javascript" src="<%= fetch_path(@service.service_slug) %>.js?courses=2011_AP_SOSC_Y_4511_HJ&preview=true"></script>
</div>

app/views/services/show.html.erb
<% title "Service - #{@service.name}" %>

<% title_html do %>
	<h1><%= @service.name %> <small>  <%= @service.live? ? "Live" : "Disabled" %> </small></h1>
<% end %>

<div class="row">
	<div class="span6">
		<h3>Service Slug</h3>
		<p><%= @service.service_slug %></p>
		<h3>Maximum No. of Entries</h3>
		<p><%= @service.show_max_entries %> per feed</p>
		<h3>Transform Course Code</h3>
		<p><%= @service.transform_course_code? ? "Yes" : "No" %></p>
		<p class="trivial">Eris will look for courses parameter with the list of comma separated courses ids and transform them into simplified version.</p>
		<p class="trivial">I.e. 2011_SC_NATS_Y_1670__6_A course id will be broken down to NATS_1670 and SC/NATS and passed on as a tag attribute to the feeds</p>

		<hr/>

	</div>
	<div class="span6">
		<h3>Assigned Data Feeds <small class="trivial">order for display</small></h3>
		<br/>
		<ul id="feeds"  data-update-url="<%= sort_feeds_service_url %>">
			<% @service.feeds.each do |feed| %>
				<%= content_tag_for :li, feed do %>
					<p><span class="handle">&equiv;</span>
					&nbsp;&nbsp;<strong><%= feed.name %></strong> <small class="trivial"><%= feed.show_title? ? "shown" : "not shown" %></small><br/>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="trivial"><%= feed.url.blank? ? "HTML Block" : feed.url  %></span></p>
				<% end %>
			<% end %>
		</ul>
		<hr/>
		<div class="css">
			<strong>CSS</strong><br/>
			<pre class="prettyprint linenums"><%= @service.css_style %></pre>
		</div>
	</div>

</div>





<div class="form-actions">


  	<%= link_to 'Edit Service', edit_service_path(@service), :class => 'btn btn-success' %>
	<%= link_to 'Back', services_path, :class => 'btn'  %>

	<div class="float-right">
		<%= link_to 'Preview', preview_service_path(@service), :class => 'btn btn-info'  %>
		<a href="#" class='btn btn-inverse'  onclick="$('#get_service_code').show();">Get The Code</a>
	</div>
</div>

<div id="get_service_code" class="hide">
	<a class="close" onclick="$('#get_service_code').hide();">&times;</a>
	<h4>Get The Code</h4>

	<pre>
	<%= <<-"CODE"

<script type="text/javascript" src="#{request.protocol}#{request.host_with_port}#{asset_path('jquery.js')}"></script>
<script type="text/javascript" src="#{root_url}fetch/#{@service.service_slug}.js?courses=LIST_COURSES_HERE"></script>




<!-- OPTIONAL DEFAULT CONTENT -->
<div id="eris_default_content">
	<div id="eris_loading_message">Loading...</div>
	<div id="eris_content_message" style="display: none;">
		<a href="https://www.library.yorku.ca">York University Libraries</a>
	</div>
</div>
<script type="text/javascript">
	setTimeout("document.getElementById('eris_loading_message').style.display='none'; document.getElementById('eris_content_message').style.display = 'block';",15000);
</script>

<!-- END OPTIONAL DEFAULT CONTENT -->

CODE
	%>

	</pre>

</div>