config/routes.rb
Eris::Application.routes.draw do


  resources :feeds

  resources :tagged_urls

  resources :services do
    post "sort_feeds", :on => :member
    get "preview", :on => :member
  end

  match "fetch/tagged_urls" => "tagged_urls#index", :format => :rss, :as => :tagged_urls_fetch
  match "fetch/:slug" => "services#fetch", :as => :fetch

  root :to => 'services#index'

  get "tags" => "tagged_urls#tags", :as => "tags"

  get "r" => "redirector#index", :as => "redirect"  
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  attr_accessible :name, :url, :cache_frequency, :description, :show_title
  alias_attribute :title, :name
  alias_attribute :feed_url, :url
  
  validates_presence_of :name
  validates_format_of :url, :with => URI::regexp(%w(http https)), :allow_blank => true
  validates_uniqueness_of :name
  
  has_many :service_feed_bridges
  has_many :services, :through => :service_feed_bridges
  
  def entries
    @entries == nil ? Array.new : @entries    
  end
  
  def entries=(entries)
    @entries = entries 
  end
  
  
  def append_query_string(query_string)
    return url if query_string.blank? || url.blank?
    
    sign = url.include?('?') ? '&' : '?'
    "#{self.url}#{sign}#{query_string}"
  end
  
  
  def fetch(query_string = nil, feed_title = nil)
    return self if url.blank?
           
    require 'feedzirra'
    require 'open-uri'
    
    feed_url = append_query_string(query_string)

    port = ENV.fetch("PORT")
    local = "http://localhost:#{port}/fetch/"
    feed_url = feed_url.sub('https://www.library.yorku.ca/eris/fetch/', local)
    begin
      raw_feed = open(feed_url) { |f| f.read }
      parsed_feed = Feedzirra::Feed.parse(raw_feed)
      self.entries = parsed_feed.entries
    rescue => e
      # error happend, tell it through a feed
      logger.error "#{e.message} for url #{feed_url} and #{title}"
      logger.error "ERROR - TIME: #{Time.now}\n"                  
      self.name = "ERIS - Error Notification"  
      self.description = "An error has occured in #{title} feed. \n\n #{feed_url} \n\n #{e.message} "
      self.entries = nil  
    end   
    
    self   
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def index
    @feeds = Feed.all
  end

  def show
    @feed = Feed.find(params[:id])
  end

  def new
    @feed = Feed.new
  end

  def create
    @feed = Feed.new(params[:feed])
    if @feed.save
      redirect_to feeds_path, :notice => "Successfully created feed."
    else
      render :action => 'new'
    end
  end

  def edit
    @feed = Feed.find(params[:id])
  end

  def update
    @feed = Feed.find(params[:id])
    if @feed.update_attributes(params[:feed])
      redirect_to feeds_path, :notice  => "Successfully updated feed."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy
    redirect_to feeds_path, :notice => "Successfully destroyed feed."
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= simple_form_for @feed, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    
	<%= f.input :name, :input_html => { :class => "span6" } %>
	<%= f.input :show_title, :label => "Display Title?"%>
	
	<%= f.input :description, :input_html => { :class => "span6"}, :label => "HTML Block"%>
	
	<%= f.input :url, :input_html => { :class => "span6" }, :label => "RSS Feed Url" %>


	<div class="control-group">
		<%= f.input :cache_frequency, :collection => [0, 15, 30, 45, 60, 90, 120, 150, 180, 360], :include_blank => false, :hint => "Cache time in minutes"%>
	</div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', feeds_path, :class => 'btn' %>

	  <%= link_to 'Destroy', feed_path(@feed), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger float-right' unless @feed.new_record?%>
    </div>

  </fieldset>
<% end %>

app/views/feeds/edit.html.erb
<% title "Edit Data Feed" %>
<%= render :partial => 'form' %>

app/views/feeds/index.html.erb
<% title "Data Feeds" %>
<% title_html do %>
	<h1>Feeds
		<%= link_to new_feed_path, :class => 'btn btn-success float-right' do%>
			<i class="icon-plus icon-white"></i>
			New Feed
		<% end %>		
	</h1>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
	  <th>Show Title?</th>
      <th>Cache</th>
	  <th>Created On</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><strong><%= feed.name %></strong><br/>
		<span class="trivial"><%= feed.url.blank? ? "HTML Block" : feed.url  %></span>
		</td>	
		<td><%= feed.show_title? ? "yes" : "no" %></td>
		<td><%= feed.cache_frequency %> min</td>
        <td><%= feed.created_at.strftime("%b %d") %></td>
        <td>
          <%= link_to 'Edit', edit_feed_path(feed), :class => 'btn btn-mini' %>
          <%= link_to "Show", feed_path(feed), :class => "btn btn-mini btn-success"%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/feeds/new.html.erb
<% title "New Data Feed" %>
<%= render :partial => 'form' %>

app/views/feeds/show.html.erb
<% title "Data Feed Details" %>

<p>
  <b>Name</b><br>
  <%= @feed.name %>
</p>

<div class="html">
	<strong>HTML Block</strong><br/>
	<pre class="prettyprint linenums"><%= @feed.description %></pre>
</div>

<p>
  <b>RSS Feed Url</b><br>
  <%= @feed.url %>
</p>

<div class="form-actions">
  <%= link_to 'Back', feeds_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_feed_path(@feed), :class => 'btn' %>
  <%= link_to 'Delete', feed_path(@feed), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>