config/routes.rb
Eris::Application.routes.draw do


  resources :feeds

  resources :tagged_urls

  resources :services do
    post "sort_feeds", :on => :member
    get "preview", :on => :member
  end

  match "fetch/tagged_urls" => "tagged_urls#index", :format => :rss, :as => :tagged_urls_fetch
  match "fetch/:slug" => "services#fetch", :as => :fetch

  root :to => 'services#index'

  get "tags" => "tagged_urls#tags", :as => "tags"

  get "r" => "redirector#index", :as => "redirect"  
end

app/models/tagged_url.rb
class TaggedUrl < ActiveRecord::Base
  attr_accessible :tag, :url, :title, :desc, :source
  paginates_per 50
  
  validates_presence_of :title, :tag, :url, :source
  validates_format_of :url, :with => URI::regexp(%w(http https))
  validates_uniqueness_of :url, :scope => :tag
  
  def self.delete_all_libguides 
    TaggedUrl.destroy_all(:source => "libguides")
  end
      
end

app/controllers/tagged_urls_controller.rb
class TaggedUrlsController < ApplicationController
  
  def index 

    if params[:tag]
       if params[:prefix] 
          tags = Array.new
          params[:tag].split(",").each do |tag|
            tags << params[:prefix] + ":" + tag.downcase
          end
       else
          tags = params[:tag]
       end
     
      @tagged_urls = TaggedUrl.where("tag in (?) ", tags)
    
      
    elsif params[:source]
      @paginated = true
      @tagged_urls = TaggedUrl.where("source = ? ", params[:source]).page(params[:page])    
      
    else
      @paginated = true
      @tagged_urls = TaggedUrl.page params[:page] 
    end
    
    respond_to do |format|
        format.html
        format.rss { render :layout => false } 
    end
  
  end
  
  def new
    @tagged_url = TaggedUrl.new
  end

  def create
    @tagged_url = TaggedUrl.new(params[:tagged_url])
    if @tagged_url.save
      redirect_to tagged_urls_url, :notice => "Successfully created tagged url."
    else
      render :action => 'new'
    end
  end

  def edit
    @tagged_url = TaggedUrl.find(params[:id])
  end

  def update
    @tagged_url = TaggedUrl.find(params[:id])
    if @tagged_url.update_attributes(params[:tagged_url])
      redirect_to tagged_urls_url, :notice  => "Successfully updated tagged url."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @tagged_url = TaggedUrl.find(params[:id])
    @tagged_url.destroy
    redirect_to tagged_urls_url, :notice => "Successfully destroyed tagged url."
  end
  
  # Get Unique Tags
  def tags
    @tagged_urls = TaggedUrl.find(:all, :group => 'tag')


    render "index"
    
  
  end
end

app/helpers/tagged_urls_helper.rb
module TaggedUrlsHelper
end

app/views/tagged_urls/_form.html.erb
<%= simple_form_for @tagged_url, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
   	  

      
	  <%= f.input :title, :input_html => { :class => "span6" } %>
	  <%= f.input :url, :input_html => {:class => "span6"} %>
	  <%= f.input :tag %>
	  <%= f.input :source, :collection => ["libguides", "wordpress"] %>
	  <%= f.input :desc, :as => :text, :input_html => { :class => "span5", :style => "height: 100px;"}%>
    

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', tagged_urls_path, :class => 'btn' %>

	  <% unless @tagged_url.new_record? %>
			<%= link_to 'Destroy', tagged_url_path(@tagged_url), :method => :delete, :confirm => 'Are you sure?', :class => 'btn float-right btn-danger' %>
	  <% end %>
    </div>
  </fieldset>
<% end %>

app/views/tagged_urls/edit.html.erb
<% title "Edit Tagged Url" %>
<% title_html do %>
	<h1>Edit Tagged Url</h1>
<% end %>
<%= render :partial => 'form' %>
<div class="row">

</div>

app/views/tagged_urls/index.html.erb
<% title "Tagged Urls"%>
<% title_html do %>
	<h1>Tagged Urls <small><%= params[:tag] if params[:tag] %> <%= params[:source] if params[:source] %></small>
		<%= link_to new_tagged_url_path, :class => 'btn btn-success float-right' do %>
			<i class="icon-plus icon-white"></i>
			New Tagged Url
		<% end %>
	</h1>
<% end %>
<a class="trivial" href="#" onclick="$('#fetch_urls').show();">Show Urls</a>
<div class="alert alert-info hide" id="fetch_urls">
	<a class="close" onclick="$('#fetch_urls').hide();"  href="#">&times;</a>
	<p><strong>URLS To Fetch Tagged Urls</strong></p>
	<p><span class="trivial">Course Guides:</span> <%= tagged_urls_fetch_url %>?prefix=c</p>
	<p><span class="trivial">Subject Guides:</span> <%= tagged_urls_fetch_url %>?prefix=s</p>	
</div>

<%= paginate @tagged_urls if @paginated %>
<p><strong>Found <%= @paginated ? @tagged_urls.total_count : @tagged_urls.count  %> items, showing <%= @tagged_urls.count%></strong></p>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Tag</th>
      <th>Title</th>
		<th>Source</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
	<% if @tagged_urls %>
	    <% @tagged_urls.each do |tagged_url| %>
	      <tr>       
	        <td><%= link_to tagged_url.tag, tagged_urls_path(:tag => tagged_url.tag) %></td>
			<td><strong><%= tagged_url.title %></strong><br/>
			<span class="trivial"><%= tagged_url.url %></span></td>
			<td><%= link_to tagged_url.source, tagged_urls_path(:source => tagged_url.source) %></td>
	        <td><%= tagged_url.created_at.strftime("%H:%M on %b %d") %></td>
	        <td>
	          <%= link_to 'Edit', edit_tagged_url_path(tagged_url), :class => 'btn btn-mini' %>	         
	        </td>
	      </tr>
	    <% end %>
	<% else %>
		<tr>
			<td class="trivial">No Urls Have Been Fetched.</td>
		</tr>
	<% end %>
  </tbody>
</table>


<%= paginate @tagged_urls if @paginated %>

app/views/tagged_urls/new.html.erb
<% title "New Tagged Url"%>
<% title_html do %>
	<h1>New Tagged Url <%= link_to 'Back', tagged_urls_path, :class => 'btn trivial' %></h1>
<% end %>
<%= render :partial => 'form' %>