config/routes.rb
Eris::Application.routes.draw do


  resources :feeds

  resources :tagged_urls

  resources :services do
    post "sort_feeds", :on => :member
    get "preview", :on => :member
  end

  match "fetch/tagged_urls" => "tagged_urls#index", :format => :rss, :as => :tagged_urls_fetch
  match "fetch/:slug" => "services#fetch", :as => :fetch

  root :to => 'services#index'

  get "tags" => "tagged_urls#tags", :as => "tags"

  get "r" => "redirector#index", :as => "redirect"  
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def title_html(&block)
    content_for(:title_html) do
      yield block
    end
  end


  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %> - Eris</title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
 	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>

	<div class="navbar navbar-inverse navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">
	      <a class="btn btn-navbar" data-toggle="collapse" data-target=".collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </a>
	      <a class="brand" href="#">Eris</a>
	      <div class="nav-collapse">
	        <ul class="nav">
	          <li><%= link_to "Services", services_path %></li>
				 <li><%= link_to "Tagged Urls", tagged_urls_path %></li>
				<li><%= link_to "Data Feeds", feeds_path %></li>
	        </ul>
	      </div>
	    </div>
	  </div>
	</div>


    <div class="container">
   		<% flash.each do |name, msg| %>
		  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
		    <a class="close" data-dismiss="alert">×</a>
		    <%= msg %>
		  </div>
		<% end %>

	 	<div class="page-header">
 	 		<%= content_tag :h1, yield(:title) if show_title? && !content_for?(:title_html) %>
			<%= yield (:title_html) if content_for?(:title_html)%>
		</div>
	  <div class="row">
	    <div class="span12"><%= yield %></div>
	  </div>

      <p>Version 1.0</p>
    </div>

  </body>
</html>

app/views/layouts/simple.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
		<style>
		.container { padding: 10px 40px; }
		hr { border-color: #EEEEEE;  border-left: 0 none;  border-right: 0 none;  border-style: solid none;   border-width: 1px 0;  margin: 18px 0; }
		h1,h2,h3,h4,h5 { font-family: Verdana; }
		.push-down { padding-top: 10px;}
		</style>
		<%= javascript_include_tag "application" %>	
	</head>
	<body>
		<div class="container">			
			<%= yield %>			
		</div>
	</body>
</html>
	